version: '3.8'
services:
  mysql:
    image: mysql:8.0
    # restart: always
    environment:
      - MYSQL_DATABASE=dlkhambenh
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - 3306

  adminer:
    image: adminer
    # restart: always
    ports:
      - '8028:8080'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: null
      DB_DATABASE: dlkhambenh
    ports:
      - 8123:3000
    expose:
      - 8123
    depends_on:
      - mysql 
  
  # NGINX reverse proxy service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   